export const SCHOOLS = [
    // 'Abbey Park High School',
    // 'Oakville Trafalgar High School',
    // 'Laurel Heights Secondary School',
    // 'Marc Garneau Collegiate Institute',
    'Dr. Frank J. Hayden Secondary School',
    'John Fraser Secondary School',
    'Bayview Secondary School',
    'GEMS Dubai American Academy',
    'Iroquois Ridge High School',
    'Markville Secondary School',
    'St. Robert Catholic High School',
    'St. Theresa of Lisieux CHS',
    'The Woodlands Secondary School',
    'University of Toronto Schools',
    'White Oaks Secondary School',
    // 'Earl Haig Secondary School',
    // 'Branksome Hall',
    // 'Upper Canada College',
    // 'Unionville High School',
    // 'Dr. Frank J. Hayden Secondary School',
    // 'Shanghai Pinghe School',
    // 'École Secondaire Publique Louis-Riel',
    // 'Holy Trinity School',
    // 'William Lyon Mackenzie Collegiate Institute',
    // 'St. Theresa of Lisieux Catholic High School',
];
