export const SCHOOLS = [
    'Oakville Trafalgar High School',
    'Marc Garneau Collegiate Institute',
    'John Fraser Secondary School',
    'Bayview Secondary School',
    'École Secondaire Publique Louis-Riel',
    'GEMS Dubai American Academy',
    'Iroquois Ridge High School',
    'Markville Secondary School',
    'St. Robert Catholic High School',
    'St. Theresa of Lisieux CHS',
    'The Woodlands Secondary School',
    'University of Toronto Schools',
    'White Oaks Secondary School',
    'Bur Oak Secondary School',
    'Bluevale Collegiate Institute',
    'Abbey Park High School',
    'Martingrove Collegiate Institute',
    'Saint John High School',
    'Thornlea Secondary School',
    'Rothesay Netherwood School',
    'Math Attack Society',
    'Dr Norman Bethune Collegiate Institute',
    'Upper Canada College',
    'Laurel Heights Secondary School',
    'Vincent Massey Secondary School',
    'Bloor Collegiate Institute',
    'Earl Haig Secondary School',
    'Leading Aces Academy',
    'Western Canada High School',
    'St Kateri Tekakwitha',
    'NA',
];

export const SCHOOL_REGION_LETTER = {
    'Oakville Trafalgar High School': 'O',
    'Marc Garneau Collegiate Institute': 'O',
    'John Fraser Secondary School': 'O',
    'Bayview Secondary School': 'O',
    'École Secondaire Publique Louis-Riel': 'O',
    'GEMS Dubai American Academy': 'I',
    'Iroquois Ridge High School': 'O',
    'Markville Secondary School': 'O',
    'St. Robert Catholic High School': 'O',
    'St. Theresa of Lisieux CHS': 'O',
    'The Woodlands Secondary School': 'O',
    'University of Toronto Schools': 'O',
    'White Oaks Secondary School': 'O',
    'Bur Oak Secondary School': 'O',
    'Bluevale Collegiate Institute': 'O',
    'Abbey Park High School': 'O',
    'Martingrove Collegiate Institute': 'O',
    'Saint John High School': 'M',
    'Thornlea Secondary School': 'O',
    'Rothesay Netherwood School': 'M',
    'Math Attack Society': 'A',
    'Dr Norman Bethune Collegiate Institute': 'O',
    'Upper Canada College': 'O',
    'Laurel Heights Secondary School': 'O',
    'Vincent Massey Secondary School': 'O',
    'Bloor Collegiate Institute': 'O',
    'Earl Haig Secondary School': 'O',
    'Leading Aces Academy': 'O',
    'Western Canada High School': 'A',
    'St Kateri Tekakwitha': 'A',
    'NA': 'N',
};

export const SCHOOL_NUMBER = {
    'NA': '000',
    'Oakville Trafalgar High School': '001',
    'Marc Garneau Collegiate Institute': '002',
    'John Fraser Secondary School': '003',
    'Bayview Secondary School': '004',
    'École Secondaire Publique Louis-Riel': '005',
    'GEMS Dubai American Academy': '006',
    'Iroquois Ridge High School': '007',
    'Markville Secondary School': '008',
    'St. Robert Catholic High School': '009',
    'St. Theresa of Lisieux CHS': '010',
    'The Woodlands Secondary School': '011',
    'University of Toronto Schools': '012',
    'White Oaks Secondary School': '013',
    'Bur Oak Secondary School': '014',
    'Bluevale Collegiate Institute': '015',
    'Abbey Park High School': '016',
    'Martingrove Collegiate Institute': '017',
    'Saint John High School': '018',
    'Thornlea Secondary School': '019',
    'Rothesay Netherwood School': '020',
    'Math Attack Society': '021',
    'Dr Norman Bethune Collegiate Institute': '022',
    'Upper Canada College': '023',
    'Laurel Heights Secondary School': '024',
    'Vincent Massey Secondary School': '025',
    'Bloor Collegiate Institute': '026',
    'Earl Haig Secondary School': '027',
    'Leading Aces Academy': '028',
    'Western Canada High School': '029',
    'St Kateri Tekakwitha': '030',
};
